name: npm test

on:
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
  NEXT_PUBLIC_FIREBASE_API_KEY: 'xxx'
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: 'xxx'
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: 'xxx'
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: 'xxx'
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: 'xxx'
  NEXT_PUBLIC_FIREBASE_APP_ID: 'xxx'
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: 'xxx'
  FIREBASE_PROJECT_ID: 'xxx'
  FIREBASE_CLIENT_EMAIL: 'xxx'
  FIREBASE_PRIVATE_KEY: 'xxx'
  FIREBASE_DATABASE_URL: 'xxx'
  NODE_ENV: 'development'

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: Install dependencies
        run: yarn
      - name: Run build
        run: yarn build
      - name: Run tests
        run: yarn test
